CREATE TABLE IF NOT EXISTS "User" (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  status BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Role (
  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS UserRole (
  user_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES "User"(user_id),
  role_id INTEGER NOT NULL REFERENCES Role(role_id),
  UNIQUE (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS Category (
  category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS FoodItem (
  food_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  description VARCHAR(255),
  price NUMERIC(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FoodItemCategory (
  fic_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  food_item_id INTEGER NOT NULL REFERENCES FoodItem(food_item_id),
  category_id INTEGER NOT NULL REFERENCES Category(category_id),
  UNIQUE (food_item_id, category_id)
);

CREATE TABLE IF NOT EXISTS Ingredient (
  ingredient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS FoodItemIngredient (
  fii_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  food_item_id INTEGER NOT NULL REFERENCES FoodItem(food_item_id),
  ingredient_id INTEGER NOT NULL REFERENCES Ingredient(ingredient_id),
  quantity_required NUMERIC(10, 2) NOT NULL,
  UNIQUE (food_item_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS Supplier (
  supplier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  contact VARCHAR(100),
  phone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS Purchase (
  purchase_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id INTEGER NOT NULL REFERENCES Supplier(supplier_id),
  purchase_date DATE NOT NULL,
  total_amount NUMERIC(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PurchaseItem (
  purchase_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id INTEGER NOT NULL REFERENCES Purchase(purchase_id),
  food_item_id INTEGER NOT NULL REFERENCES FoodItem(food_item_id),
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(10, 2) NOT NULL,
  UNIQUE (purchase_id, food_item_id)
);

CREATE TABLE IF NOT EXISTS Stock (
  stock_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_id INTEGER UNIQUE NOT NULL REFERENCES Ingredient(ingredient_id),
  quantity_available NUMERIC(10, 2) NOT NULL,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Order" (
  order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  order_type VARCHAR(20) NOT NULL,
  total_amount NUMERIC(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS OrderItem (
  order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES "Order"(order_id),
  food_item_id INTEGER NOT NULL REFERENCES FoodItem(food_item_id),
  quantity INTEGER NOT NULL,
  price_at_time NUMERIC(10, 2) NOT NULL,
  UNIQUE (order_id, food_item_id)
);

CREATE TABLE IF NOT EXISTS Payment (
  payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount NUMERIC(10, 2) NOT NULL,
  method VARCHAR(50) NOT NULL,
  order_id INTEGER REFERENCES "Order"(order_id),
  payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS OrderPayment (
  order_payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES "Order"(order_id),
  payment_id INTEGER NOT NULL REFERENCES Payment(payment_id)
);

CREATE TABLE IF NOT EXISTS InventoryLog (
  log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_id INTEGER NOT NULL REFERENCES Ingredient(ingredient_id),
  user_id INTEGER NOT NULL REFERENCES "User"(user_id),
  action_type VARCHAR(50) NOT NULL,
  quantity_change NUMERIC(10, 2) NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Unit (
  unit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_name VARCHAR(50) NOT NULL,
  conversion_rate NUMERIC(10, 4)
);

CREATE TABLE IF NOT EXISTS ItemUnit (
  item_unit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  food_item_id INTEGER NOT NULL REFERENCES FoodItem(food_item_id),
  unit_id INTEGER NOT NULL REFERENCES Unit(unit_id),
  is_default BOOLEAN DEFAULT FALSE,
  UNIQUE (food_item_id, unit_id)
);

INSERT INTO Role (role_id, role_name) VALUES
  (1, 'Admin'), (2, 'Manager'), (3, 'Chef'), (4, 'Kitchen Staff'),
  (5, 'Waiter'), (6, 'Cashier'), (7, 'Delivery Driver'),
  (8, 'Inventory Control'), (9, 'Supplier Relations'), (10, 'Marketing')
ON CONFLICT (role_id) DO NOTHING;

INSERT INTO "User" (user_id, full_name, email, password_hash, status) VALUES
  (1, 'Local Admin', 'admin@food.com', '$2b$10$skP1wFldJ21jg0ViqJhCFeRfLFfV6LMT8MDenCyfeuvystJd4.ttG', TRUE)
ON CONFLICT (email) DO UPDATE SET
  password_hash = EXCLUDED.password_hash,
  status = TRUE;

INSERT INTO UserRole (user_id, role_id)
SELECT user_id, 1 FROM "User" WHERE email = 'admin@food.com'
ON CONFLICT (user_id, role_id) DO NOTHING;

INSERT INTO Unit (unit_id, unit_name, conversion_rate) VALUES
  (1, 'kg', 1.0000), (2, 'gram', 0.0010), (3, 'liter', 1.0000),
  (4, 'ml', 0.0010), (5, 'piece', NULL), (6, 'dozen', 12.0000),
  (7, 'pack', NULL), (8, 'box', NULL), (9, 'lb', 0.4536),
  (10, 'cup', 0.2366)
ON CONFLICT (unit_id) DO NOTHING;

INSERT INTO Supplier (supplier_id, name, contact, phone) VALUES
  (1, 'Dairy King Distributors', 'Mr. Patel', '555-1001'),
  (2, 'Fresh Veggie Market', 'Ms. Lin', '555-1002'),
  (3, 'Prime Meats Corp', 'Mr. Sanchez', '555-1003'),
  (4, 'Global Spice Traders', 'Ms. Kaur', '555-1004'),
  (5, 'Beverage Systems Inc', 'Mr. Jones', '555-1005')
ON CONFLICT (supplier_id) DO NOTHING;

INSERT INTO Category (category_id, name, description) VALUES
  (1, 'Appetizers', 'Small bites to start the meal.'),
  (2, 'Main Dishes', 'The primary course of the meal.'),
  (3, 'Desserts', 'Sweet items after the meal.'),
  (4, 'Beverages', 'Hot and cold drinks.'),
  (5, 'Salads', 'Fresh and healthy dishes.'),
  (6, 'Vegetarian', 'Dishes without meat.')
ON CONFLICT (category_id) DO NOTHING;

INSERT INTO Ingredient (ingredient_id, name, description) VALUES
  (1, 'All-Purpose Flour', 'Base for breads and pastas.'),
  (2, 'Salt', 'Basic seasoning.'),
  (3, 'Sugar', 'Sweetener.'),
  (4, 'Fresh Chicken Breast', 'Protein for main dishes.'),
  (5, 'Ground Beef', 'Meat for burgers and sauces.'),
  (6, 'Roma Tomatoes', 'Base for sauces and salads.'),
  (7, 'Onion', 'Basic aromatic vegetable.'),
  (8, 'Olive Oil', 'Cooking and finishing oil.'),
  (9, 'Mozzarella Cheese', 'Cheese for pizzas and dishes.'),
  (10, 'Lettuce', 'Base for salads.')
ON CONFLICT (ingredient_id) DO NOTHING;

INSERT INTO FoodItem (food_item_id, name, description, price) VALUES
  (101, 'Classic Cheeseburger', 'Beef patty with cheese, lettuce, and tomato.', 12.99),
  (102, 'Margherita Pizza', 'Tomato sauce, mozzarella, and basil.', 15.50),
  (103, 'Chicken Caesar Salad', 'Grilled chicken, lettuce, and parmesan.', 10.99),
  (104, 'Garlic Knots', 'Oven-baked knots with garlic butter.', 5.00),
  (105, 'Chocolate Cake', 'Rich chocolate dessert.', 8.50),
  (106, 'Iced Tea', 'Freshly brewed cold tea.', 3.00)
ON CONFLICT (food_item_id) DO NOTHING;

INSERT INTO FoodItemCategory (food_item_id, category_id) VALUES
  (101, 2), (102, 2), (102, 6), (103, 5), (104, 1), (105, 3), (106, 4)
ON CONFLICT (food_item_id, category_id) DO NOTHING;

INSERT INTO FoodItemIngredient (food_item_id, ingredient_id, quantity_required) VALUES
  (101, 5, 0.33), (101, 6, 0.05), (101, 10, 0.05),
  (102, 1, 0.20), (102, 6, 0.15), (102, 9, 0.20),
  (103, 4, 0.15), (103, 10, 0.10), (104, 1, 0.10),
  (105, 1, 0.08), (105, 3, 0.05), (106, 3, 0.01)
ON CONFLICT (food_item_id, ingredient_id) DO NOTHING;

INSERT INTO Stock (ingredient_id, quantity_available) VALUES
  (1, 150), (2, 80), (3, 100), (4, 75), (5, 90),
  (6, 120), (7, 70), (8, 60), (9, 85), (10, 110)
ON CONFLICT (ingredient_id) DO NOTHING;

INSERT INTO Purchase (purchase_id, supplier_id, purchase_date, total_amount) VALUES
  (5001, 1, CURRENT_DATE - 10, 450.00),
  (5002, 2, CURRENT_DATE - 7, 315.75),
  (5003, 3, CURRENT_DATE - 3, 620.50)
ON CONFLICT (purchase_id) DO NOTHING;

INSERT INTO PurchaseItem (purchase_id, food_item_id, quantity, unit_price) VALUES
  (5001, 102, 20, 8.00), (5002, 103, 30, 4.00), (5003, 101, 40, 7.00)
ON CONFLICT (purchase_id, food_item_id) DO NOTHING;

INSERT INTO "Order" (order_id, order_type, total_amount) VALUES
  (7001, 'Dine-in', 28.49), (7002, 'Takeaway', 15.99)
ON CONFLICT (order_id) DO NOTHING;

INSERT INTO OrderItem (order_id, food_item_id, quantity, price_at_time) VALUES
  (7001, 101, 1, 12.99), (7001, 102, 1, 15.50), (7002, 103, 1, 10.99)
ON CONFLICT (order_id, food_item_id) DO NOTHING;

INSERT INTO Payment (payment_id, amount, method, order_id) VALUES
  (8001, 28.49, 'Cash', 7001), (8002, 15.99, 'Card', 7002)
ON CONFLICT (payment_id) DO NOTHING;

INSERT INTO InventoryLog (ingredient_id, user_id, action_type, quantity_change) VALUES
  (1, 1, 'Stock added', 150), (4, 1, 'Stock added', 75), (5, 1, 'Stock added', 90)
ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('role', 'role_id'), 10, TRUE);
SELECT setval(pg_get_serial_sequence('unit', 'unit_id'), 10, TRUE);
SELECT setval(
  pg_get_serial_sequence('"User"', 'user_id'),
  (SELECT MAX(user_id) FROM "User"),
  TRUE
);
SELECT setval(pg_get_serial_sequence('supplier', 'supplier_id'), (SELECT MAX(supplier_id) FROM Supplier), TRUE);
SELECT setval(pg_get_serial_sequence('category', 'category_id'), (SELECT MAX(category_id) FROM Category), TRUE);
SELECT setval(pg_get_serial_sequence('ingredient', 'ingredient_id'), (SELECT MAX(ingredient_id) FROM Ingredient), TRUE);
SELECT setval(pg_get_serial_sequence('fooditem', 'food_item_id'), (SELECT MAX(food_item_id) FROM FoodItem), TRUE);
SELECT setval(pg_get_serial_sequence('purchase', 'purchase_id'), (SELECT MAX(purchase_id) FROM Purchase), TRUE);
SELECT setval(pg_get_serial_sequence('"Order"', 'order_id'), (SELECT MAX(order_id) FROM "Order"), TRUE);
SELECT setval(pg_get_serial_sequence('payment', 'payment_id'), (SELECT MAX(payment_id) FROM Payment), TRUE);
